pub const SignalError = error{
    InvalidArgument,
    InvalidState,
    InvalidKey,
    InvalidSignature,
    InvalidMessage,
    InvalidKeyIdentifier,
    InvalidType,
    InvalidUtf8String,
    InsufficientOutputSize,
    ProtobufError,
    LegacyCiphertextVersion,
    UnknownCiphertextVersion,
    UnrecognizedMessageVersion,
    DuplicateMessage,
    UntrustedIdentity,
    SessionNotFound,
    InvalidSession,
    NoKeyTypeIdentifier,
    SignatureMismatch,
    FingerprintIdentifierMismatch,
    FingerprintVersionMismatch,
    NullParameter,
    CallbackError,
    VerifyFailed,
    PaddingError,
    IdentityElement,
    WeakPublicKey,
    EncodingError,
    OutOfMemory,
    Overflow,
    Unsupported,
};

pub const ErrorCode = enum(u32) {
    none = 0,
    unknown = 1,
    invalid_state = 2,
    internal_error = 3,
    null_parameter = 4,
    invalid_argument = 5,
    invalid_type = 6,
    invalid_utf8_string = 7,
    insufficient_output_size = 8,
    protobuf_error = 9,
    legacy_ciphertext_version = 10,
    unknown_ciphertext_version = 11,
    unrecognized_message_version = 12,
    invalid_message = 13,
    invalid_key = 14,
    invalid_signature = 15,
    fingerprint_identifier_mismatch = 16,
    fingerprint_version_mismatch = 17,
    untrusted_identity = 18,
    invalid_key_identifier = 19,
    session_not_found = 20,
    invalid_session = 21,
    duplicate_message = 22,
    callback_error = 23,
    verify_failed = 24,
    _,
};
